name: Latest blog post workflow

on:
  schedule:
    # 每天 UTC 时间 0 点运行（北京时间 8 点）
    - cron: '0 0 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://deusyu.app/feed.xml"
          max_post_count: 6
          template: "- [$title]($url) - $date"
          date_format: "yyyy-MM-dd"
          commit_message: "docs: update blog posts"
